"use client";
import { useState } from "react";
import "./globals.css";
import "@/styles/antd/index.scss";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import Layout from "@/components/layout";
import { useServerInsertedHTML } from "next/navigation";
import { createCache, extractStyle, StyleProvider } from "@ant-design/cssinjs";
const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const [cache] = useState(() => createCache());

  useServerInsertedHTML(() => {
    return (
      <script
        dangerouslySetInnerHTML={{
          __html: `</script>${extractStyle(cache)}<script>`,
        }}
      />
    );
  });
  return (
    <html lang="en">
      <body className={inter.className}>
        <StyleProvider cache={cache}>
          <Layout>{children}</Layout>
        </StyleProvider>
      </body>
    </html>
  );
}
